/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.*;
/**
 *
 * @author GIANELLI
 */
public class InscripcionVista extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo;
    private CursadaData cursadaData;
    private MateriaData materiaData;
    private AlumnoData alumnoData;
    //private ArrayList<Cursada> listaCursada;
    //private ArrayList<Materia> listaMaterias;
    private ArrayList<Alumno> listaAlumnos;
    private Conexion con;

    /**
     * Creates new form InscripcionVista
     */
    public InscripcionVista() {
        initComponents();
        con = new Conexion("jdbc:mysql://localhost:3306/universidadg2", "root", "");
        modelo = new DefaultTableModel();

//        cursadaData = new CursadaData(con);
//        listaCursada = (ArrayList) cursadaData.obtenerCursadas();
//
//        materiaData = new MateriaData(con);
//        listaMaterias = (ArrayList)materiaData.obtenerMaterias();

        alumnoData = new AlumnoData(con);
        listaAlumnos = (ArrayList) alumnoData.obtenerAlumnos();
        
        cargarAlumnos();
        armarCabeceraTabla();
        //cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupInscripciones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboAlumno = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tMaterias = new javax.swing.JTable();
        jbInscribir = new javax.swing.JButton();
        jbAnularI = new javax.swing.JButton();
        jRinscriptas = new javax.swing.JRadioButton();
        jRnoInscriptas = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jBsalir = new javax.swing.JButton();

        setTitle("TP-Transversal");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("FORMULARIO DE INSCRIPCION");

        jLabel2.setText("ALUMNO");

        comboAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAlumnoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("LISTADO DE MATERIAS");

        tMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tMaterias);

        jbInscribir.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbInscribir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salvar.png"))); // NOI18N
        jbInscribir.setText("INSCRIBIR");
        jbInscribir.setEnabled(false);
        jbInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInscribirActionPerformed(evt);
            }
        });

        jbAnularI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbAnularI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        jbAnularI.setText("ANULAR INSCRIPCION");
        jbAnularI.setEnabled(false);
        jbAnularI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularIActionPerformed(evt);
            }
        });

        groupInscripciones.add(jRinscriptas);
        jRinscriptas.setText("INSCRIPTAS");
        jRinscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRinscriptasActionPerformed(evt);
            }
        });

        groupInscripciones.add(jRnoInscriptas);
        jRnoInscriptas.setText("NO INSCRIPTAS");
        jRnoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRnoInscriptasActionPerformed(evt);
            }
        });

        jLabel4.setText("SELECCIONE QUE MATERIAS DESEA VER :");

        jBsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N
        jBsalir.setText("VOLVER");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jbInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbAnularI)
                        .addGap(18, 18, 18)
                        .addComponent(jBsalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jRinscriptas)
                        .addGap(70, 70, 70)
                        .addComponent(jRnoInscriptas)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(comboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRnoInscriptas)
                    .addComponent(jRinscriptas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAnularI)
                    .addComponent(jbInscribir)
                    .addComponent(jBsalir))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAlumnoActionPerformed
        //cargarDatos();
    }//GEN-LAST:event_comboAlumnoActionPerformed

    private void jRnoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRnoInscriptasActionPerformed
       cargarDatosNoInscriptas();
        jbInscribir.setEnabled(true);
        jbAnularI.setEnabled(false);
    }//GEN-LAST:event_jRnoInscriptasActionPerformed

    private void jRinscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRinscriptasActionPerformed
        cargarDatosInscriptas();
        jbInscribir.setEnabled(false);
        jbAnularI.setEnabled(true);
    }//GEN-LAST:event_jRinscriptasActionPerformed

    private void jbInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirActionPerformed
           int filaSelect = tMaterias.getSelectedRow();
           if(filaSelect != -1){
               Alumno a = (Alumno)comboAlumno.getSelectedItem();
               if(a!=null){
                   
                   int idMateria = (Integer)modelo.getValueAt(filaSelect, 0);
                   String nombreMat = (String)modelo.getValueAt(filaSelect, 1);
                   Materia m = new Materia(nombreMat, idMateria);
                   
                   Cursada c = new Cursada(a, m, 0);
                   cursadaData = new CursadaData(con);
                   cursadaData.guardarCursada(c);
                   borrarFilasTablas();
               }
           }
           JOptionPane.showMessageDialog(this, "Inscripcion Completa");
    }//GEN-LAST:event_jbInscribirActionPerformed

    private void jbAnularIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularIActionPerformed
        int filaSelect = tMaterias.getSelectedRow();
           if(filaSelect != -1){
               Alumno a = (Alumno)comboAlumno.getSelectedItem();
               if(a!=null){
                   
                   int idMateria = (Integer)modelo.getValueAt(filaSelect, 0);
                   
               
                   cursadaData = new CursadaData(con);
                   cursadaData.borrarCursadaDeUnaMateriaDeunAlumno(a.getIdAlumno(), idMateria);
                   borrarFilasTablas();
               }
           }
           JOptionPane.showMessageDialog(this, "Se Anulo Inscripcion Correctamente");
    }//GEN-LAST:event_jbAnularIActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBsalirActionPerformed
    
    private void cargarAlumnos() {
        for(Alumno item:listaAlumnos){
            comboAlumno.addItem(item);         
        }     
    }
    private void armarCabeceraTabla() {
        ArrayList<Object> columns = new ArrayList<>();
        columns.add("Id");
        columns.add("Nombre");
        columns.forEach((it) -> {
            modelo.addColumn(it);
        });
        tMaterias.setModel(modelo);
    }
    
    public void borrarFilasTablas() {
        int a = modelo.getRowCount() - 1; // -1 indice de ultima fila.
        for (int i = a; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }
    
    private void cargarDatosInscriptas() {
        borrarFilasTablas();
        cursadaData = new CursadaData(con);
        Alumno select = (Alumno)comboAlumno.getSelectedItem();
        List<Materia> lista = cursadaData.obtenerMateriasCursadas(select.getIdAlumno());
        
        for(Materia m:lista){
            modelo.addRow(new Object[]{m.getIdMateria(),m.getNombreMateria()});
        }
    }
    
    private void cargarDatosNoInscriptas() {
        borrarFilasTablas();
        cursadaData = new CursadaData(con);
        Alumno select = (Alumno)comboAlumno.getSelectedItem();
        List<Materia> lista = cursadaData.obtenerMateriasNOCursadas(select.getIdAlumno());
        
        for(Materia m:lista){
            modelo.addRow(new Object[]{m.getIdMateria(),m.getNombreMateria()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Alumno> comboAlumno;
    private javax.swing.ButtonGroup groupInscripciones;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRinscriptas;
    private javax.swing.JRadioButton jRnoInscriptas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAnularI;
    private javax.swing.JButton jbInscribir;
    private javax.swing.JTable tMaterias;
    // End of variables declaration//GEN-END:variables
}
